import { useState, useEffect, useRef, useMemo } from 'react';
import { Link } from 'react-router-dom';
import { FiboGrid, ColumnDef } from 'fibogrid';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { ArrowLeft, Download, Palette, Copy, Check } from 'lucide-react';
import { ThemeToggle } from '@/components/ThemeToggle';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Separator } from '@/components/ui/separator';
import { toast } from '@/hooks/use-toast';

import { themePresets } from './ThemeBuilderPresets';

// Sample data
const sampleData = [
  { id: '1', country: 'Argentina', sport: '🏇 Horse Racing', athlete: 'Andrew Unalkat', total: 66392, year2023: 34090, year2022: 32302 },
  { id: '2', country: 'Portugal', sport: '🏓 Ping Pong', athlete: 'Lucy Connell', total: 28748, year2023: 21697, year2022: 7051 },
  { id: '3', country: 'Argentina', sport: '⛷️ Skiing', athlete: 'Lucy Jett', total: 46362, year2023: 6898, year2022: 39464 },
  { id: '4', country: 'France', sport: '🎳 Bowling', athlete: 'Grace Dallas', total: 18026, year2023: 15968, year2022: 2058 },
  { id: '5', country: 'Germany', sport: '🎯 Darts', athlete: 'Mia Fletcher', total: 68503, year2023: 33622, year2022: 34881 },
  { id: '6', country: 'Germany', sport: '🎾 Tennis', athlete: 'Isabella Black', total: 36078, year2023: 5098, year2022: 30980 },
  { id: '7', country: 'Peru', sport: '🚴 Cycling', athlete: 'Dimple Gunner', total: 53582, year2023: 35580, year2022: 18002 },
  { id: '8', country: 'Sweden', sport: '🏉 Rugby', athlete: 'Ruby Cohen', total: 51049, year2023: 8899, year2022: 42150 },
  { id: '9', country: 'USA', sport: '🏈 Football', athlete: 'Tom Brady', total: 82050, year2023: 41025, year2022: 41025 },
  { id: '10', country: 'Brazil', sport: '⚽ Soccer', athlete: 'Neymar Jr', total: 75000, year2023: 37500, year2022: 37500 },
];

type ThemeValue = typeof themePresets.default.theme;

export default function ThemeBuilder() {
  const [theme, setTheme] = useState<ThemeValue>(themePresets.default.theme);
  const [selectedPreset, setSelectedPreset] = useState<string>('default');
  const [themeName, setThemeName] = useState('my-custom-theme');
  const [copied, setCopied] = useState(false);
  const styleRef = useRef<HTMLStyleElement | null>(null);

  // Apply theme to preview via style tag
  useEffect(() => {
    if (!styleRef.current) {
      styleRef.current = document.createElement('style');
      styleRef.current.id = 'theme-builder-preview';
      document.head.appendChild(styleRef.current);
    }
    
    // Generate CSS variables block
    // We target .fibogrid.theme-builder-preview to scope these variables
    // to the preview grid instance.
    const css = `
/* Theme Builder Preview Scope */
.fibogrid.theme-builder-preview {
${Object.entries(theme)
  .filter(([key]) => key.startsWith('--fibogrid-'))
  .map(([key, value]) => `  ${key}: ${value};`)
  .join('\n')}
}

/* Also apply to body to ensure portals (like popovers, menus) inherit vars */
body {
${Object.entries(theme)
  .filter(([key]) => key.startsWith('--fibogrid-popover-') || key.startsWith('--fibogrid-column-menu-') || key.startsWith('--fibogrid-tooltip-'))
  .map(([key, value]) => `  ${key}: ${value};`)
  .join('\n')}
}
`;

    styleRef.current.textContent = css;

    return () => {
      // Cleanup on unmount
      if (styleRef.current && document.head.contains(styleRef.current)) {
        document.head.removeChild(styleRef.current);
        styleRef.current = null;
      }
    };
  }, [theme]);

  const applyPreset = (presetKey: string) => {
    const preset = themePresets[presetKey];
    if (preset) {
      setTheme(preset.theme);
      setSelectedPreset(presetKey);
      setThemeName(preset.name.toLowerCase().replace(/\s+/g, '-'));
      toast({ title: 'Preset Applied', description: `${preset.name} theme loaded` });
    }
  };

  const updateTheme = (key: keyof ThemeValue, value: string) => {
    setTheme(prev => ({ ...prev, [key]: value }));
    setSelectedPreset('custom');
  };

  const generateCSS = () => {
    return `/* FiboGrid Custom Theme: ${themeName} */
/* Generated by FiboGrid Theme Builder */

.fibogrid.${themeName} {
${Object.entries(theme)
  .map(([key, value]) => `  ${key}: ${value};`)
  .join('\n')}
}

/* Add this class to your FiboGrid component: className="${themeName}" */
`;
  };

  const downloadCSS = () => {
    const css = generateCSS();
    const blob = new Blob([css], { type: 'text/css' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${themeName || 'custom-theme'}.css`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast({ title: 'CSS Downloaded', description: `Theme saved as ${themeName || 'custom-theme'}.css` });
  };

  const copyToClipboard = async () => {
    const css = generateCSS();
    await navigator.clipboard.writeText(css);
    setCopied(true);
    toast({ title: 'Copied!', description: 'CSS copied to clipboard' });
    setTimeout(() => setCopied(false), 2000);
  };

  const ColorInput = ({ label, key, description }: { label: string; key: keyof ThemeValue; description?: string }) => (
    <div className="space-y-2">
      <div className="flex items-center justify-between">
        <Label htmlFor={key} className="text-sm font-medium">{label}</Label>
        {description && <span className="text-xs text-muted-foreground">{description}</span>}
      </div>
      <div className="flex gap-2">
        <Input
          id={key}
          type="color"
          value={theme[key] || '#ffffff'}
          onChange={(e) => updateTheme(key, e.target.value)}
          className="w-16 h-10 cursor-pointer"
        />
        <Input
          type="text"
          value={theme[key] || ''}
          onChange={(e) => updateTheme(key, e.target.value)}
          className="flex-1 font-mono text-sm"
          placeholder="#000000"
        />
      </div>
    </div>
  );

  const NumberInput = ({ label, key, min, max, step, unit = 'px' }: { 
    label: string; 
    key: keyof ThemeValue; 
    min?: number; 
    max?: number; 
    step?: number;
    unit?: string;
  }) => {
    const currentValue = theme[key];
    const numericValue = unit ? parseFloat(currentValue) || 0 : parseFloat(currentValue) || 0;
    
    return (
      <div className="space-y-2">
        <Label htmlFor={key} className="text-sm font-medium">{label}</Label>
        <div className="flex gap-2 items-center">
          <Input
            id={key}
            type="number"
            value={numericValue}
            onChange={(e) => {
              const val = e.target.value;
              updateTheme(key, unit ? `${val}${unit}` : val);
            }}
            min={min}
            max={max}
            step={step || 1}
            className="flex-1"
          />
          {unit && <span className="text-sm text-muted-foreground w-8">{unit}</span>}
        </div>
      </div>
    );
  };

  const columns: ColumnDef<typeof sampleData[0]>[] = useMemo(() => [
    { 
      field: 'country', 
      headerName: 'Country', 
      sortable: true,
      width: 140,
      pinned: 'left'
    },
    { 
      field: 'sport', 
      headerName: 'Sport', 
      sortable: true,
      width: 160,
    },
    { 
      field: 'athlete', 
      headerName: 'Name', 
      sortable: true,
      width: 160,
    },
    { 
      field: 'total', 
      headerName: 'Total winnings', 
      sortable: true,
      width: 150,
      cellRenderer: ({ value }) => `$${value.toLocaleString()}`
    },
    { 
      field: 'year2023', 
      headerName: '2023 winnings', 
      sortable: true,
      width: 150,
      cellRenderer: ({ value }) => `$${value.toLocaleString()}`
    },
    { 
      field: 'year2022', 
      headerName: '2022 winnings', 
      sortable: true,
      width: 150,
      cellRenderer: ({ value }) => `$${value.toLocaleString()}`
    },
  ], []);

  return (
    <div className="min-h-screen bg-background">
      <header className="sticky top-0 z-50 border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="px-6 py-3 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Link to="/" className="flex items-center gap-2">
              <Palette className="h-6 w-6 text-primary" />
              <span className="font-semibold text-lg">FiboGrid Theme Builder</span>
            </Link>
            <Badge variant="outline" className="text-xs">
              Beta
            </Badge>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="ghost" size="sm" asChild>
              <Link to="/docs">
                <ArrowLeft className="h-4 w-4 mr-2" />
                Back to Docs
              </Link>
            </Button>
            <ThemeToggle />
          </div>
        </div>
      </header>

      <div className="container mx-auto px-6 py-6">
        <div className="grid lg:grid-cols-[400px_1fr] gap-6">
          {/* Controls Panel */}
          <ScrollArea className="h-[calc(100vh-120px)]">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Palette className="h-5 w-5" />
                  Theme Settings
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                {/* Preset Selector */}
                <div className="space-y-2">
                  <Label className="text-sm font-medium">Theme Presets</Label>
                  <div className="grid grid-cols-2 gap-2">
                    {Object.entries(themePresets)
                      .filter(([key]) => key !== 'custom')
                      .map(([key, preset]) => (
                        <Button
                          key={key}
                          variant={selectedPreset === key ? 'default' : 'outline'}
                          size="sm"
                          onClick={() => applyPreset(key)}
                          className="h-auto py-2 flex flex-col items-start"
                        >
                          <span className="font-medium text-xs">{preset.name}</span>
                          <span className="text-[10px] text-muted-foreground">{preset.description}</span>
                        </Button>
                      ))}
                  </div>
                </div>

                <Separator />

                {/* Theme Name */}
                <div className="space-y-2">
                  <Label htmlFor="themeName" className="text-sm font-medium">Theme Class Name</Label>
                  <Input
                    id="themeName"
                    value={themeName}
                    onChange={(e) => setThemeName(e.target.value)}
                    placeholder="my-custom-theme"
                    className="font-mono"
                  />
                </div>

                <Separator />

                {/* Theme Controls */}
                <Tabs defaultValue="colors" className="w-full">
                  <TabsList className="grid w-full grid-cols-3">
                    <TabsTrigger value="colors">Colors</TabsTrigger>
                    <TabsTrigger value="borders">Borders</TabsTrigger>
                    <TabsTrigger value="layout">Layout</TabsTrigger>
                  </TabsList>

                  <TabsContent value="colors" className="space-y-4 mt-4">
                    <div>
                      <h3 className="font-semibold mb-3 text-sm">Background & Surface</h3>
                      <div className="space-y-3">
                        <ColorInput label="Background" key="--fibogrid-bg" />
                        <ColorInput label="Surface" key="--fibogrid-surface" />
                        <ColorInput label="Surface Hover" key="--fibogrid-surface-hover" />
                        <ColorInput label="Surface Selected" key="--fibogrid-surface-selected" />
                      </div>
                    </div>

                    <Separator />

                    <div>
                      <h3 className="font-semibold mb-3 text-sm">Text Colors</h3>
                      <div className="space-y-3">
                        <ColorInput label="Text" key="--fibogrid-text" />
                        <ColorInput label="Text Secondary" key="--fibogrid-text-secondary" />
                        <ColorInput label="Text Muted" key="--fibogrid-text-muted" />
                      </div>
                    </div>

                    <Separator />

                    <div>
                      <h3 className="font-semibold mb-3 text-sm">Primary Colors</h3>
                      <div className="space-y-3">
                        <ColorInput label="Primary" key="--fibogrid-primary" />
                        <ColorInput label="Primary Hover" key="--fibogrid-primary-hover" />
                        <ColorInput label="Primary Active" key="--fibogrid-primary-active" />
                      </div>
                    </div>
                  </TabsContent>

                  <TabsContent value="borders" className="space-y-4 mt-4">
                    <div>
                      <h3 className="font-semibold mb-3 text-sm">General Borders</h3>
                      <div className="space-y-3">
                        <ColorInput label="Border" key="--fibogrid-border" />
                        <ColorInput label="Border Strong" key="--fibogrid-border-strong" />
                        <ColorInput label="Cell Border Right" key="--fibogrid-cell-border-right" />
                        <ColorInput label="Cell Border Bottom" key="--fibogrid-cell-border-bottom" />
                        <ColorInput label="Header Border Bottom" key="--fibogrid-header-border-bottom" />
                      </div>
                    </div>

                    <Separator />

                    <div>
                      <h3 className="font-semibold mb-3 text-sm">Border Radius</h3>
                      <div className="space-y-3">
                        <NumberInput label="Radius SM" key="--fibogrid-radius-sm" min={0} max={20} />
                        <NumberInput label="Radius MD" key="--fibogrid-radius-md" min={0} max={20} />
                        <NumberInput label="Radius LG" key="--fibogrid-radius-lg" min={0} max={20} />
                      </div>
                    </div>
                  </TabsContent>

                  <TabsContent value="layout" className="space-y-4 mt-4">
                    <div>
                      <h3 className="font-semibold mb-3 text-sm">Heights</h3>
                      <div className="space-y-3">
                        <NumberInput label="Header Height" key="--fibogrid-header-height" min={20} max={100} />
                        <NumberInput label="Row Height" key="--fibogrid-row-height" min={20} max={100} />
                        <NumberInput label="Cell Padding" key="--fibogrid-cell-padding" min={4} max={32} />
                      </div>
                    </div>

                    <Separator />

                    <div>
                      <h3 className="font-semibold mb-3 text-sm">Typography</h3>
                      <div className="space-y-3">
                        <div className="space-y-2">
                          <Label className="text-sm font-medium">Font Family</Label>
                          <Input
                            value={theme['--fibogrid-font-family']}
                            onChange={(e) => updateTheme('--fibogrid-font-family', e.target.value)}
                            placeholder="Inter, sans-serif"
                          />
                        </div>
                        <NumberInput label="Font Size" key="--fibogrid-font-size" min={10} max={20} />
                      </div>
                    </div>
                  </TabsContent>
                </Tabs>

                <Separator />

                {/* Actions */}
                <div className="flex gap-2">
                  <Button variant="outline" size="sm" onClick={copyToClipboard} className="flex-1">
                    {copied ? <Check className="h-4 w-4 mr-2" /> : <Copy className="h-4 w-4 mr-2" />}
                    {copied ? 'Copied!' : 'Copy CSS'}
                  </Button>
                  <Button size="sm" onClick={downloadCSS} className="flex-1">
                    <Download className="h-4 w-4 mr-2" />
                    Download
                  </Button>
                </div>
              </CardContent>
            </Card>
          </ScrollArea>

          {/* Preview Panel */}
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>Live Preview</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="h-[600px] border rounded-lg overflow-hidden flex flex-col">
                  <div className="flex-1 min-h-0 bg-[hsl(var(--fibogrid-bg))] text-[hsl(var(--fibogrid-text))]">
                    <FiboGrid
                      className="theme-builder-preview h-full"
                      rowData={sampleData}
                      columnDefs={columns}
                      getRowId={(row) => row.id}
                      rowSelection="multiple"
                      showToolbar={true}
                      showStatusBar={true}
                      pagination={true}
                      paginationPageSize={25}
                    />
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Generated CSS */}
            <Card>
              <CardHeader>
                <CardTitle>Generated CSS</CardTitle>
              </CardHeader>
              <CardContent>
                <ScrollArea className="h-[300px] rounded-md border p-4">
                  <pre className="text-xs font-mono">
                    <code>{generateCSS()}</code>
                  </pre>
                </ScrollArea>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}
